#!/bin/bash
SERVER_HOST="127.0.0.1"
SERVER_PORT="12345"
DOC_SIZE=$1
REPEAT=5
FILE_SUFF=$2
SEED=-1
NUMBER_OF_CLIENTS=$3
CLEANNING=$4
THREADCOUNT=$5
for (( CLIENT_ID=1; CLIENT_ID<=$NUMBER_OF_CLIENTS; CLIENT_ID++ ))
do
  java -jar ./jars/WoCoClient.jar $SERVER_HOST $SERVER_PORT $DOC_SIZE $REPEAT $FILE_SUFF $SEED $CLIENT_ID $NUMBER_OF_CLIENTS $CLEANNING $THREADCOUNT &
done
wait
