#!/bin/bash
SERVER_HOST=$1
SERVER_PORT="9000"
CLEAN=$2    #true
THREADS=$3
FIXED_NUMBER_OF_CLIENTS=$4      #true
DOC_SIZE=$5
FILE_SUFF=$6
java -jar ./jars/WoCoServer.jar $SERVER_HOST $SERVER_PORT $CLEAN "$THREADS" "$FIXED_NUMBER_OF_CLIENTS" $DOC_SIZE $FILE_SUFF