#!/bin/bash
SERVER_HOST=$1
SERVER_PORT="9000"
CLEAN=$2    #true
THREADS=$3
DOC_SIZE=$4
FILE_SUFF=$5
MIN_CLIENTS=$6
MAX_CLIENTS=$7

for ((NUMBER_OF_CLIENTS=$MIN_CLIENTS; NUMBER_OF_CLIENTS<=$MAX_CLIENTS; NUMBER_OF_CLIENTS*=2))
do
  for (( REPEAT=1; REPEAT<=5; REPEAT++ ))
  do
    java -jar ./jars/WoCoServer.jar $SERVER_HOST $SERVER_PORT $CLEAN "$THREADS" "$NUMBER_OF_CLIENTS" $DOC_SIZE $FILE_SUFF $REPEAT
    wait
  done
  wait
done
echo "Done"

