#!/bin/bash
SERVER_HOST=$1
SERVER_PORT="9000"
CLEAN=$2    #true
THREADS=$3
DOC_SIZE=$4
FILE_SUFF=$5
OPS=$6
NUMBER_OF_CLIENTS=$7

for (( REPEAT=1; REPEAT<=3; REPEAT++ ))
do
  date +"%T"
  java -jar ./jars/WoCoServer.jar $SERVER_HOST $SERVER_PORT $CLEAN "$THREADS" "$NUMBER_OF_CLIENTS" $DOC_SIZE $FILE_SUFF $REPEAT $OPS
  wait
done
wait

